urls.py
from django.urls import path
from . import views
from .views import IndexView,linename_autocomplete

app_name = 'trains'
urlpatterns = [
        path('',views.IndexView.as_view(),name='index'),
        path('linename_autocomplete/',views.linename_autocomplete,name = 'linename_autocomplete'),
]

models.py
from django.db import models


# Create your models here.
class TrainLine(models.Model):
    trainID = models.CharField(max_length=5)
    trainName = models.CharField(max_length=200)
    trainNameEng = models.CharField(max_length=200)
    trainCompany = models.CharField(max_length=200)
    trainSearch = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.trainName


class StationList(models.Model):
    stationNo = models.CharField(max_length=6)
    trainName = models.CharField(max_length=200)
    stationID = models.CharField(max_length=6)
    stationName = models.CharField(max_length=200)
    stationDistince = models.CharField(max_length=200)
    stationNameEng = models.CharField(max_length=200)

    def __str__(self):
        return '<div id=row><div id=stationID>'+self.stationNo+'</div><div id=stationName>'+self.stationName+'</div><div id=stationNameEng>'+self.stationNameEng+'</div></div>'

forms.py
from dal import autocomplete
from django import forms
from .models import TrainLine

class TrainListForm(forms.ModelForm):
    city_form = forms.ModelChoiceField(
            queryset=TrainLine.objects.all(),
            widgets=autocomplete.ModelSelect2(url='linename_autocomplete')
        )
    class Meta:
        model = TrainLine
        fields = ('__all__')

views.py
from .models import TrainLine, StationList
import json
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from pykakasi import kakasi

kakasi = kakasi()
kakasi.setMode('H', 'a')
kakasi.setMode('K', 'a')
kakasi.setMode('J', 'a')
conv = kakasi.getConverter()


class IndexView(ListView):
    template_name = 'trains/index.html'
    context_object_name = 'station_list'

    def get_queryset(self):
        q = self.request.GET.get('name')
        if q != None:
            return StationList.objects.filter(trainName__istartswith=q).order_by('stationNo')
        else:
            return None


def linename_autocomplete(request):
    q = request.GET.get('term')
    if q != None:
        lines = TrainLine.objects.filter(trainSearch__istartswith=conv.do(q))[:10]
        results = []
        for line in lines:
            line_json = {}
            line_json['id'] = line.trainName
            line_json['label'] = line.trainName
            line_json['value'] = line.trainName
            results.append(line_json)
        data = json.dumps(results)
    else:
        results = []
        data = json.dumps(results)
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)

templates/trains/index.html
{% block script %}
	<link rel="stylesheet" href="http://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
	<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
	<script>
	$(function(){
		$(".trainName").autocomplete({
			source: "/trains/linename_autocomplete/",
			minLength: 2,
		});
	});
	</script>
	<style type="text/css">
	#stations{
	width: 500px;
	color: #000000;
	padding:0px;
	display: table;
	border: 1px solid black;
	}
	#row  {
	display: table-row;
	}
	#stationID {
	padding:0px;
	width: 100px;
	background:#FFFFFF;
	border: 1px solid black;
	display: table-cell;
	}
	#stationNameEng {
	padding:0px;
	width: 200px;
	background:#FFFFFF;
	border: 1px solid black;
	display: table-cell;
	}
	#stationName {
	padding:0px;
	width: 200px;
	background:#FFFFFF;
	border: 1px solid black;
	display: table-cell;
	}
	</style>
{% endblock %}

<div class="ui-widget">
	<form method="get" action="{% url 'trains:index' %}">{% csrf_token %}
	<label for="train">鉄道名	:</label>
	<input id="train" class="trainName" name="name">
	<input type="submit" value="表示">
	</form>
</div>
<br>
{% if station_list %}
<div>
	<p>{{ request.GET.name }}の線路</p>
	<p><div id=stations>
	<div id=row><div id=stationID>駅ID</div><div id=stationName>駅名</div><div id=stationNameEng>駅名（ENG）</div></div>
	{% for station in station_list %}
	{{ station |safe }}
	{% endfor %}
	</div></p>
</div>
{% elif 'name' in request.GET %}
	<p>{{ request.GET.name }}の検索結果</p>
	<p>No data.</p>
{% endif %}
<div>
	※pykakasiを活用し漢字、英字、ひらかな、カタカナにも対応<br>
	以下の線路がアップデータされました。<br>
	・東葉高速線<br>
	・多摩線<br>
	・江ノ島線<br>
	・小田原線<br>
	・成田スカイアクセス線<br>
	・千葉線<br>
	・東成田線<br>
	・金町線<br>
	・京成本線<br>
	・押上線<br>
</div>